SECRET_KEY: "sk_test_k4NSYvGPhpjwV3FkLODtgnHE00FByJkroA"
PUBLISHABLE_KEY: "pk_test_D0KRm4duYy2S9jRzzjM93rsz00xwjVyIUk"
AWS_ACCESS_KEY: "AKIAXEDC4BZ276YCQIKB"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "flixlessons"
AWS_REGION: "us-east-1"